### ISSUE TITLE
Add npm.shrinkwrap until we migrate to YARN

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#103]
If we fix #100, or add something that replaces it, we should freeze the dependency tree by running `npm shrinkwrap`, see https://docs.npmjs.com/cli/shrinkwrap for more information.

**Comment by bex1** [comment]
@buren has this been solved now when we have migrated?

**Comment by buren** [comment]
Yep, no shrinkwrap, but yarn.lock :)
