### ISSUE TITLE
Update start page for logged in/not logged in users

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#105]
**Comment:**
When you're not logged in to the app you should not be able to go to the profile (since there is none :blush:). 

**Definition of done:**
New layout with dummy text for now. Add a localization string for it and we'll update it later on with the correct content! 

**Added value:**
Enhanced UX

https://app.asana.com/0/215405294182400/234902084122341

**Comment by bellevik** [comment]
![logged in - mobile](https://cloud.githubusercontent.com/assets/3898301/22062010/d5c9a640-dd77-11e6-86da-90367aa6ddd3.png)
![logged in](https://cloud.githubusercontent.com/assets/3898301/22062012/d803a3d4-dd77-11e6-98b7-62eb7cd27b88.png)
![not logged in - mobile](https://cloud.githubusercontent.com/assets/3898301/22062014/da71b494-dd77-11e6-9a23-8fd0b8955896.png)
![not logged in](https://cloud.githubusercontent.com/assets/3898301/22062018/dd439192-dd77-11e6-9765-136a921b13ab.png)

**Comment by tikkat** [comment]
@Ekman1991 As written in Slack, the buttons in the header are not completely done yet, great work otherwise tho! 💪

**Comment by tikkat** [comment]
Done ✅
