### ISSUE TITLE
RESTful routes

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#108]
Jacob provides details

**Comment by bex1** [comment]
Please details ?
Include userid in routes right?

**Comment by tikkat** [comment]
@buren

**Comment by buren** [comment]
@bex1 I think we basically should use the same routes as the backend has. Doesn't need to be exactly the same, but structurally :)

**Comment by bex1** [comment]
Changed routes to

user/:user-id/
user/:user-id/jobs
