### ISSUE TITLE
Job application page - redesign and click expansion

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#111]
**Comments:**
In the old frontend there is an expansion option for seeing more details. I made this design for mobile to show my intention with the job application page. Ping me if there is a need of a desktop design as well.

**Definition of Done:**
Working functionality as in old frontend design. Both implemented for logged in users and NUX users.

**Added value:**
Design improvement. Clearer UX.

https://app.asana.com/0/215405294182400/232728682288991

**Comment by bellevik** [comment]
![job application page](https://cloud.githubusercontent.com/assets/3898301/22062287/48bbdde8-dd79-11e6-8533-a0dbe66e1148.png)
![job application page - expanded](https://cloud.githubusercontent.com/assets/3898301/22062289/4ac5ced2-dd79-11e6-9894-91cda6da10bd.png)
![job application - nux](https://cloud.githubusercontent.com/assets/3898301/22062293/4df3f868-dd79-11e6-9f08-ccc77882b6af.png)
