### ISSUE TITLE
Redesign confirmation pages

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#113]
@tikkat we need to provide screenshots for this :) Do we have them yet?

**Comment by tikkat** [comment]
<img width="1440" alt="screen shot 2017-01-19 at 14 40 29" src="https://cloud.githubusercontent.com/assets/3510315/22108829/42fe4fd0-de55-11e6-9a59-04cc38118fae.png">

**Comment by bex1** [comment]
Solved and implemented
