### ISSUE TITLE
Redesign sidebar navigation and language selector

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#116]
## Old design

<img width="525" alt="screen shot 2016-12-20 at 15 28 56" src="https://cloud.githubusercontent.com/assets/922411/22022879/127e40b4-dcc4-11e6-9b92-da2b2ccb0297.png">
<img width="567" alt="screen shot 2016-12-20 at 15 27 40" src="https://cloud.githubusercontent.com/assets/922411/22022884/14b9e6d0-dcc4-11e6-83b1-e2e4adf4acaf.png">

**Comment by bex1** [comment]
Closing since done
