### ISSUE TITLE
Refactor sass so all buttons/labels are unified and styled in the same place

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#132]
**Comment: **
Right now different designs are used for buttons and labels, we would like this to be centralized. 

**Definition of Done: **
Designs refactored to use BEM (if this is the SCSS convention we are following) so one design can be used throughout all of the application

**Added value: **
More maintainable code, easier to add a new component since it is clearer where to look for it.

**Comment by bex1** [comment]
Button part is done

**Comment by tikkat** [comment]
So much love <3
