### ISSUE TITLE
User profile page on Safari looks weird. See attached screenshot.

### ISSUE THREAD

**Issue by Ekman1991** [justarrived/just-match-web#133]
<img width="606" alt="screen shot 2017-01-19 at 10 22 40" src="https://cloud.githubusercontent.com/assets/3540718/22100888/572b878a-de31-11e6-9210-7bf8cb80daf3.png">

**Comment by tikkat** [comment]
@Ekman1991 awesome that you're adding this one! Don't forget the P3 label :) Might seem unnecessary for now but will be handy with time so we can see how many bugs we are working at in comparison to new feature development

**Comment by bex1** [comment]
The radio button has been fixed. However I do not know why it looks strange on Safari on  the auto complete dropdown implemented by boris. The placeholder shows when it should not show. Can my fellow Safari users help with this?

Cheers

@Ekman1991 
@bellevik

**Comment by bex1** [comment]
@Ekman1991 Was this resolved?

**Comment by Ekman1991** [comment]
Can't figure out what is causing this.

Whenever the user is choosing something from the dropdown, the method `onDestinationChange()` is called. Maybe a starting point?
