### ISSUE TITLE
Redesign of sidebar navigation and language selector

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#136]
**Comment:**
The current sidebar is using the old design and color scheme. By updating it we will have a more unified product and better look-and-feel

**Definition of Done:**

- The design should be as of the design mockups attached below. The functionality should work the same way as it already does :)
- Both the language selector and the hamburger sidebar menu should be implemented (see the two separate designs below)

**Added value:**
Clearer design and more simplistic design

### Language selector
![spr-k-meny---gr- 1](https://cloud.githubusercontent.com/assets/3510315/22150147/ca740924-df17-11e6-90f3-4654571aacd8.jpg)

### Hamburger sidebar menu
![meny---gr- 1](https://cloud.githubusercontent.com/assets/3510315/22150142/c274f6b6-df17-11e6-89d5-ea7fed0df4a8.jpg)

**Comment by Ekman1991** [comment]
What will this button do?

![screen shot 2017-01-26 at 18 37 01](https://cloud.githubusercontent.com/assets/3540718/22342965/8639f64a-e3f6-11e6-8b99-581f9da855d9.png)
