### ISSUE TITLE
On form 422 response scroll to top of form and display message

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#156]
When, for example, registering as a user and you get validation errors like "email already exists", you aren't scrolled to the top of the page. Meaning that it could seems to the user that the save button just doesn't work (validation errors might be outside of the current viewport)

**Definition of done:**

- Scroll to the top of the form
- Display a message like "Please review the below errors"

**Comment by bellevik** [comment]
Maybe add something similar for when clicking the "Sign up" button without filling out all required fields? Just disabling the button without giving some context might be confusing?

**Comment by bex1** [comment]
An error "There are some errors, please review them above." is shown above the button.
Also a loading gif is in place.

I am not sure about the idea to scroll to top.
The error might aswell be at the bottom of the form.

@buren
