### ISSUE TITLE
Job header not showing for past jobs

### ISSUE THREAD

**Issue by bvangelov** [justarrived/just-match-web#166]
The pink header with the job title, salary and other info is not showing for past jobs (either for users or companies).

Steps to reproduce:
1. Log in as teodor.tunev@wintrgarden.com / pass: 12345678
2. Go to My jobs / History
3. Click any job

The screen briefly flashes with the pink header, but then it hides.

**Comment by bex1** [comment]
@bellevik kan du kolla detta?
