### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#17]
Noticed

> remove global error message in console in case of exception; Think for better solution
> - https://github.com/justarrived/just-match-web/blob/master/app/config/global-exception-handler.ts#L4

Seems like Sentry could be a good fit. Explicit Angular 2 support and a fair price :)
https://docs.sentry.io/clients/javascript/integrations/angular2/

**Comment by belev** [comment]
If you want you can create account there. We will create ticket for integrating Sentry and include it in some of the other sprints. @buren what do you think?

**Comment by buren** [comment]
Closed by #179
