### ISSUE TITLE
Add "Upcoming jobs" to job listing section

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#171]
**Description:**
Since there are so few current jobs in the platform right now we intend to show "Upcoming jobs" in the job listing screen as well. Note that these jobs won't have as much information as the "current jobs", you will have the name of the position and in what city it will be performed.

This is the current design:
![screen shot 2017-01-30 at 14 43 00](https://cloud.githubusercontent.com/assets/3510315/22425240/72510bda-e6fa-11e6-8212-8fdc11b8ce68.png)

We want the titles "Current jobs" and "Upcoming jobs" in the new design

**Comment by tikkat** [comment]
@buren What information do we have about the upcoming jobs? :)

**Comment by buren** [comment]
@tikkat this is already implemented (though quite naively), so the information available can be checked by setting a job to `upcoming` and then making a request :) 

That said we should, no doubt, discuss what fields should (not) be returned. 

Generally I think we should return quite a lot of information even things we aren't certain of and have a warning ⚠ sign stating that the information isnt final..
