### ISSUE TITLE
api-call.service can not use JARoutes constants

### ISSUE THREAD

**Issue by bex1** [justarrived/just-match-web#181]
** Description **

When using the JARoutes constants in this service it wont be injected in other services.
The bug is very cryptic and only happens in this service.

I have no idea how to resolve this.

https://github.com/justarrived/just-match-web/blob/develop/src/app/services/api-call.service.ts#L118

All input appreciated.

**Comment by buren** [comment]
Did you find a fix?:)

**Comment by bex1** [comment]
Yes, it was solved when i solved the aot issue by removing cyclic dependencies.
