### ISSUE TITLE
[Backend / Discuss] Why do we not allow the user to have an already existing phone number?

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#193]
![image](https://cloud.githubusercontent.com/assets/3510315/22518197/0d9d8f3e-e8ac-11e6-8504-23554b4aacd0.png)

**Comment by tikkat** [comment]
@buren I am thinking that maybe two persons are sharing the same number and that they both should be able to create an account. Is there a reason for why we can't use the same number for several people? :)

**Comment by tikkat** [comment]
@bex1 @buren @bellevik @Ekman1991 could you please discuss this one during the morning standup today? My opinion is that we should allow the same phone number for several users because that makes most sense from a UX perspective, but if there's a good technical reason for not doing that we'll keep it like this. I think we should explain that to the user in that case, let me know if I should take a look at copy in that case :)

**Comment by buren** [comment]
Discussed with Anna... we're keeping the unique constraint, due to SMS notifications and retaining the ability to login with your phone number.
