### ISSUE TITLE
Jobs not displayed on job listing page and pagination 1 / 0

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#194]
**Comment from the testing session:**
[Philip]: I created account. Logged in. Clicked on “Find Jobs”. No jobs displayed. (Have not accepted the confirmation mail from sign-in (if there are any?)) (Error message: [blocked]Access to geolocation was blocked over insecure connection to http://localhost:4200. )

**Comment by bex1** [comment]
There are no jobs in the future in the database. Only future jobs wll be displayed.
Passed jobs will not be displayed anymore.

The error message for geolocation is due to your connection.

**Comment by bex1** [comment]
@tikkat
