### ISSUE TITLE
The user should be able to navigate to their profile settings from the side menu

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#196]
**Comment:**
Apparently this disappeared during a companyUser-fix, let's just add "Edit profile" in the side menu again :) 

Side menu: 
![image](https://cloud.githubusercontent.com/assets/3510315/22518464/f3337252-e8ac-11e6-8a96-b7b4c5b60ada.png)

**Comment by bex1** [comment]
Solved earlier today
