### ISSUE TITLE
Remove skill number from the skill list on the profile page

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#199]
The users do not need to know about the number we have given the different skills, it's a little bit confusing :)

**Comment by tikkat** [comment]
@buren is this something that is handled by the backend?

**Comment by bellevik** [comment]
From what I can see in the Frontend, the name that gets sent back with the request contains the number. If we need it in the backend, I can simply remove it from the frontend, otherwise, it's probably better if it is removed from the backend altogether.

**Comment by bex1** [comment]
@bellevik The real data in the launched app backend will not include such numbers.
