### ISSUE TITLE
Prefill the name and email address from the user when they are trying to contact Just Arrived from the app

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#201]
**Comment:**
Right now the user have to fill in their name and email when they want to send us a message:
![image](https://cloud.githubusercontent.com/assets/3510315/22519056/44581bc2-e8af-11e6-9673-04c9a0fa5e2d.png)

Since we already have this information we could remove these two fields and just ask for the message text that they want to send us

**Comment by bex1** [comment]
They should be able to contact us even when not logged in right?
But we can prefill the info if logged in.
@tikkat 
@buren
