### ISSUE TITLE
Unclear error message, the user can't see what it is that needs to be fixed in order to proceed

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#224]
![image](https://cloud.githubusercontent.com/assets/3510315/22564049/4206e400-e983-11e6-87cd-8b08eebc6096.png)

**Comment by bex1** [comment]
@tikkat What other input was provided?

**Comment by tikkat** [comment]
@bex1 it's probably the bank details that are the cause of the problem, it is when I have the wrong number of digits there that I get the error message. This one needs better copy :) Is it a catch-all scenario for submit? Maybe we need to add more specific error messages?

**Comment by bex1** [comment]
Ah I see that only a clearing number of 4 digits and account number of 7 didigts are allowed now in the api.
This has to be changed @buren

These formats has to be supported:
Affärsbankernas standard: CCCC – XX XXX XX (4 + 7 = 11 siffror)
Handelsbankens standard: CCCC – XXX XXX XXX (4 + 9 = 13 siffror)
Sparbankernas (Swedbank) standard: CCCC-C XXX XXX XXXX (5 + 10 = 15 siffror)

Swedish accounts are what should be used right?
@tikkat 
@buren

**Comment by bex1** [comment]
@buren Also errors for fields account_number and account_clearing_number are not sent to the frontend on PATCH /api/v1/users/:id

**Comment by buren** [comment]
@bex1 will fix!
