### ISSUE TITLE
Create preview page where the user can review his/her profile before applying for jobs

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#227]
**Comment:**
The users would like to preview their profile so they can be sure of what is displayed to the recruiters when they are applying for a specific job. How should this be represented? Take inspiration from LinkedIn for example:
![image](https://cloud.githubusercontent.com/assets/3510315/22566085/ed3b3bda-e98a-11e6-8d95-07aded184d9c.png)

**Definition of done:**
Desktop and mobile design

**Comment by bex1** [comment]
First the reqruiters need a candidate view in an admin design.
Then we can look at this I think.

**Comment by tikkat** [comment]
Great feedback! The admin interface will be looked at by Johan, whereas this task refers to the design in the frontend. Are you suggesting that we don't know what info we can preview so far @bex1?

**Comment by bex1** [comment]
Im just suggesting that the candidate view needs to be designed first sp we know how the preview should look since it should mimic that view :) @tikkat
