### ISSUE TITLE
Responsiveness problems on smaller devices for job listing page

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#229]
The text on the job listing page doesn't really fit on smaller screen sizes:
![image](https://cloud.githubusercontent.com/assets/3510315/22580668/8a5cf3f0-e9da-11e6-8288-69f772fb6825.png)

This image shows how it looks like on a iPhone SE (dimensions 320 x 568). 

In order to fix this bug the text should adapt to the screen size for the smaller screen sizes :)

**Comment by tikkat** [comment]
@bellevik Wasn't it you that worked on this one before? :) That's the reason why I assigned you, ignore it otherwise. I'm thinking that it's enough to do something about the date text, either by sending it a little bit to the left or resizing it in order to get rid of the design bug

**Comment by Ekman1991** [comment]
There is an active PR (https://github.com/justarrived/just-match-web/pull/231) for this. However, the tooltip for the map is overflowing on the viewport. Don´t want to fiddle around in the CSS for tooltip so I opened an issue for that one instead (https://github.com/justarrived/just-match-web/issues/230)
