### ISSUE TITLE
Add "Fields of Interests" to profile settings page

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#236]
**Comment:**
We want to ask the user for their interests the same way as we are asking for their skills. It works exactly the same as skills and user skills does, see the user documentation.

Just add it above skills in the following place in the app: 
![image](https://cloud.githubusercontent.com/assets/3510315/22695722/fda48f48-ed4b-11e6-8136-3b43454167f5.png)

**Comment by tikkat** [comment]
@bex1 something that you could have a look at? :) Should be fairly straight forward, let me know if anything is unclear

**Comment by buren** [comment]
As for the API fields of interests uses the same metaphor as skills & languages:

```
User --* UserInterest(level, level_by_admin) *-- Interest
```
instead of
```
User --* UserSkill(prof, prof_by_admin) *-- Skill
``` 

_API Docs_: https://api.justarrived.se/api_docs/1.0/user_interests.html
