### ISSUE TITLE
More prominent "confirm"/"will perform" button on jobs page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#247]
<img width="651" alt="screen shot 2017-02-08 at 15 57 24" src="https://cloud.githubusercontent.com/assets/922411/22742532/61d76df2-ee17-11e6-8f8c-c6cdb3a99d11.png">

"Ge besked" is a bit too incognito...

cc @tikkat, @andrew-hawari

**Comment by tikkat** [comment]
Waiting for design
