### ISSUE TITLE
Reset password is broken

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#251]
**Comment:**
When I've been sent the reset password email to my email address I am being redirected to the start page of the app:
![image](https://cloud.githubusercontent.com/assets/3510315/22751980/fd27ed44-ee36-11e6-83d3-e00f654c47c5.png)

I have no possibility to change my password.

**Comment by tikkat** [comment]
@buren is this somehting that is handled by the backend?

**Comment by tikkat** [comment]
This is the URL I get in the browser:
https://app.justarrived.se/#/reset_password/7e1609f983c109d56c6700922419b3284ab5df7b58f79960087cc5d16e1b4eb497010ca438096beb048474af0bb1a383e4ffafee008d2aa230729dc5d1e25cf0

**Comment by bex1** [comment]
The link sent out is wrong. It should be https://app.justarrived.se/reset-password/7e1609f983c109d56c6700922419b3284ab5df7b58f79960087cc5d16e1b4eb497010ca438096beb048474af0bb1a383e4ffafee008d2aa230729dc5d1e25cf0
