### ISSUE TITLE
One language is shown as [object Object] in the language drop-down

### ISSUE THREAD

**Issue by bellevik** [justarrived/just-match-web#255]
On the Create Account page, the language select dropdown shows the first option as [object Object]
<img width="470" alt="screen shot 2017-02-09 at 9 53 19 am" src="https://cloud.githubusercontent.com/assets/3898301/22775888/e614bd36-eead-11e6-9ef8-bee86ebcf585.png">

**Comment by bellevik** [comment]
The problem exists when using another language than English (the app language). Also, the same issue creates more problems:
<img width="480" alt="screen shot 2017-02-09 at 11 11 06 am" src="https://cloud.githubusercontent.com/assets/3898301/22778905/ef5da096-eeb8-11e6-8967-f4567259b7d9.png">

**Comment by buren** [comment]
Duplicate of #234 :)
