### ISSUE TITLE
Job description does not preserve new-lines

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#268]
<img width="583" alt="screen shot 2017-02-09 at 17 14 50" src="https://cloud.githubusercontent.com/assets/922411/22791930/4a57c8be-eeeb-11e6-98b2-52b8dcffe238.png">

We should preserve new-lines that are in text blobs (HTML does not preserve them).

__Possible solutions__:

1. Format the text blob client side and replace new lines `\n` & `\r\n` with `<br>` etc.
2. Have the backend send an additional field `description_html`.

What do you think?

**Comment by buren** [comment]
The code for _Solution 1_ could look something like:

```javascript
function simpleFormat(string) {
    const simpleFormatReg1 = /\r\n?/g
    const simpleFormatReg2 = /\n\n+/g
    const simpleFormatReg3 = /([^\n]\n)(?=[^\n])/g
    let fstr = string
    fstr = fstr.replace(simpleFormatReg1, "\n")          // \r\n and \r -> \n
    fstr = fstr.replace(simpleFormatReg2, "</p>\n\n<p>") // 2+ newline  -> paragraph
    fstr = fstr.replace(simpleFormatReg3, "$1<br/>")     // 1 newline   -> br
    fstr = "<p>" + fstr + "</p>"
    return fstr
}
```

**Comment by bex1** [comment]
@buren I think the backend should send html. 
This enables us to add more structure such as bulletpoints etc.

**Comment by buren** [comment]
👍 👍

**Comment by buren** [comment]
@bex1 the backend no sends an additional key `*_html` for all long strings.
