### ISSUE TITLE
Add Angular Material to frontend

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#272]
**Comment:**
The new frontend is using material design to big extent. Me, Sebastian and Daniel suggests that we should add it to the frontend.

Example screens:
![image](https://cloud.githubusercontent.com/assets/3510315/22827417/1a35c16a-ef98-11e6-970e-8d1f21067a2a.png)

![image](https://cloud.githubusercontent.com/assets/3510315/22827430/29b790be-ef98-11e6-807c-4e8fc1d15523.png)

_EDIT_ (buren):

Material2:
- Github: https://github.com/angular/material2
- Docs: https://material.angular.io

**Comment by tikkat** [comment]
@buren Do you have anything you would like to say about this decision? :) otherwise I'd say that we add it right away!

**Comment by buren** [comment]
@tikkat :100: :+1:

**Comment by buren** [comment]
Material2:
- Github: https://github.com/angular/material2
- Docs: https://material.angular.io
