### ISSUE TITLE
Design touch-up: Job Listing View

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#279]
**Comment:**
The new updated design is al little different from what already is in place, this task will therefore focus on the design. The "Karta" section should remain as is already, nothing new needs to be done with it that is :)

![job listing](https://cloud.githubusercontent.com/assets/3510315/22884286/755cdc64-f1f4-11e6-90c8-c7689804a431.png)

**New functionality:**
- Date displayed for each task in new format:
![image](https://cloud.githubusercontent.com/assets/3510315/22884373/e61a3cb2-f1f4-11e6-9725-e459105d1bbb.png)

- Translation button:
![image](https://cloud.githubusercontent.com/assets/3510315/22884355/d39d8d3c-f1f4-11e6-93df-c29e7f9c255f.png)

**Subtasks:**
- [ ]  Design update
- [ ]  Add the Translate button, it should translate the content to the language that is currently set by the user:
![image](https://cloud.githubusercontent.com/assets/3510315/22884355/d39d8d3c-f1f4-11e6-93df-c29e7f9c255f.png)

**Comment by buren** [comment]
Awesome spec 👍

**Comment by tikkat** [comment]
Note to self: the buttons in the pagination container won't work on mobile, too much of a hassle to redesign due to this. Keeping the arrows as it is
