### ISSUE TITLE
Welcome Onboarding Wizard

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#281]
**Comment:**
An overview can be found here:
https://app.sketchviewer.com/sketches/58a1aa5870b69c0011b0ed22/latest/

Let's discuss race conditions on the go, this task is probably not a one-man-show :)
The popup should appear the first time a user signs in to his/her account. We should then validate how many more times it should be shown through user testing sessions, maybe first time is enough.

**Design - Desktop:**
First time user login:
![first time user login](https://cloud.githubusercontent.com/assets/3510315/22893669/aeb07f58-f216-11e6-8964-3f7b8b7cb82d.png)
![base info 1](https://cloud.githubusercontent.com/assets/3510315/22893751/f65cd02c-f216-11e6-814c-f2390c4abd6a.png)
![base info 2a](https://cloud.githubusercontent.com/assets/3510315/22893756/f80fe29c-f216-11e6-95d1-ec4e92c300a5.png)
![base info 2b](https://cloud.githubusercontent.com/assets/3510315/22893761/fabda5f6-f216-11e6-92ac-3273688a7e30.png)
![base info 3a](https://cloud.githubusercontent.com/assets/3510315/22893767/fd5b65f0-f216-11e6-95d8-04cbc5a866f9.png)
![base info 3b](https://cloud.githubusercontent.com/assets/3510315/22893771/ffe5b08c-f216-11e6-9ad4-54efa6edc462.png)
![base info 4](https://cloud.githubusercontent.com/assets/3510315/22893772/01b8f248-f217-11e6-87f8-b16576041b9b.png)

**Design - mobile:**
![mobile - first time login](https://cloud.githubusercontent.com/assets/3510315/22893988/a5ec1872-f217-11e6-8f40-0235201aea31.png)
![mobile - base info 1](https://cloud.githubusercontent.com/assets/3510315/22894004/aec4f0e0-f217-11e6-8b40-f9004fcf3409.png)
![mobile - base info 2a](https://cloud.githubusercontent.com/assets/3510315/22894009/b367c834-f217-11e6-9bf0-6a490501bc51.png)
![mobile - base info 2b](https://cloud.githubusercontent.com/assets/3510315/22894011/b521163a-f217-11e6-8f0b-b876ed06f939.png)
![mobile - base info 3a](https://cloud.githubusercontent.com/assets/3510315/22894014/b774669e-f217-11e6-8ba3-d61f5c927ab7.png)
![mobile - base info 3b](https://cloud.githubusercontent.com/assets/3510315/22894018/b9111fe2-f217-11e6-9420-7d68d2a0cc01.png)
![mobile - base info 4](https://cloud.githubusercontent.com/assets/3510315/22894020/bc967716-f217-11e6-9e47-2f2f870c600f.png)

**Definition of Done:** 
- [ ] Design as mockups, both desktop and mobile
- [ ] Google Analytics - Discuss with dev team about what data we want to collect before implementing

**Specification:**
- [ ] When moving to "Next" step, all information is saved.
- [ ] When closing the modal (Cross) all information filled in so far should be saved
- [ ]

**Comment by buren** [comment]
Really love the design 😻 Though as we discussed today we _might_ implement the overlays as separate pages if its a significant time win + makes it easier to maintain. However since we're planning to add Angular Material #272 and I took a quick 👀 on their docs and they have a component dialog that looks kinda what we're after.

**Comment by bex1** [comment]
Yea the dialog should do it. Worked with it before in Angular 1. @buren

**Comment by bex1** [comment]
This design is not on par with the new design direction and it wont be implemented.
