### ISSUE TITLE
Profile Settings Page

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#282]
**Comment:**
Desktop:
![profile page](https://cloud.githubusercontent.com/assets/3510315/22894391/1cfafd9c-f219-11e6-9f44-846bb369d756.png)
![profile - edit status](https://cloud.githubusercontent.com/assets/3510315/22894399/2359a968-f219-11e6-882d-1a3ff4e0a966.png)
![profile - edit personal presentation](https://cloud.githubusercontent.com/assets/3510315/22894401/24b2b80e-f219-11e6-93f0-559fdb55ba14.png)
![profile - edit language skills](https://cloud.githubusercontent.com/assets/3510315/22894402/25ea4d40-f219-11e6-9576-8ae823f072c2.png)
![profile - edit general skills](https://cloud.githubusercontent.com/assets/3510315/22894404/27974472-f219-11e6-88a7-5e8fddf29419.png)

Mobile:
![mobile - profile page](https://cloud.githubusercontent.com/assets/3510315/22894425/39a48d14-f219-11e6-8fa3-dfefa7c0996b.png)

**Comment by tikkat** [comment]
Todo:
- [ ] Design Account Tab page (I will create it)

**Comment by bex1** [comment]
Closed in favor of #456
