### ISSUE TITLE
Design Account Tab page for Profile settings view

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#283]
**Comment:**
This view is still missing for the new updated design delivered by Emma, I am on it! //Tikka

**Comment by tikkat** [comment]
This is one way we could go about it:
![image](https://cloud.githubusercontent.com/assets/3510315/22898108/5de4ca06-f226-11e6-8b97-be6779bdecdf.png)

I want to discuss this with you other guys and will keep it here for now until next standup meeting :)

**Comment by buren** [comment]
I really like the design and the emphasis on privacy 👍though I'm not sure about "Private" as the tab label. It's not obvious what fields you will find there. 


Googles "mixed"  approach is quite interesting mixing large icons with smaller links. 
![screenshot_20170213-211408](https://cloud.githubusercontent.com/assets/922411/22901382/c4531ecc-f231-11e6-84f1-7deb9b863f28.png)

Not saying we've should copy that but thought it might be an inspiration to our "profile landing page"

**Comment by tikkat** [comment]
Good input! I agree :)
