### ISSUE TITLE
Users shouldn't be able to apply for jobs if they haven't filled in the minimum requirements in their profile page

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#294]
**Comment:**
There should be a guard when applying for a job, all the mandatory fields in the profile settings page  should be filled in before the user can apply for a job. Otherwise the recruiters will get applications from profiles without any data, with is worth 0 ;) 

Me and @buren discussed that the check should be done by the API. The frontend should send the user to the profile settings page.

**Comment by tikkat** [comment]
I would like to discuss this one tomorrow (Wednesday)

**Comment by buren** [comment]
@tikkat I'm not completely sure this should be labeled `P2` (`P3` seems more appropriate) I think we can live without this feature a few more weeks (we don't have _that_ many applicants yet). Lets double check with @annahornmark about that though :)

Changing the label to P3, feel free to disagree with me! 😄

**Comment by annahornmark** [comment]
We can live with it until we import all the users from Wintrgarden, so maximum 2 weeks since that's what I promised the users in question @buren @tikkat 
However, new unverified users register every day, so the sooner the better of course since this is THE primary incentive for them to update their profile

**Comment by buren** [comment]
Thanks @annahornmark for the input! We'll make sure to plan for it!

@tikkat lets discuss and set a MVP for this tomorrow (it doesn't have to be perfect just good enough) and we'll take from there

**Comment by buren** [comment]
🎉 ⭐️
