### ISSUE TITLE
Add global error handler 

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#299]
**Comment:**
We need a unified way to handle errors in the frontend and to present the error sent from the API.

**Comment by bex1** [comment]
A form error should be presented next to the relevant field if there is one. What happens when there is no such field on the current page? For example when applying/confirming for a job with missing user information.

Other errors should be routed to some error page? What is displayed there?
@buren @tikkat

**Comment by buren** [comment]
@bex1 I think that if there are "general" errors in a "regular" form (like the edit profile page) then we can display the error message(s) just above the submit/save button. 

__Model/resource errors__:
- For "Apply for job" button then I think we basically can do the same thing (display an error message near the button)
- For "Confirm job offer" where we have a dialog, we could either;
  1. Close the dialog and display the error message as described above
  2. Display a error message above the button in the dialog

__General errors__:
There aren't that many cases (can think of four).
1. On Login required and Token expired: Redirect to login page.
2. On Not found and Invalid Credentials: Display error message near the save/submit button.

Seems like we can get away a fairly easy set of rules that encompasses all of the above cases.

**Comment by bex1** [comment]
@buren Great work summarizing that. It will be helpful. Will also make sure to include it in the developer guide. 👍

**Comment by buren** [comment]
@bex1 would probably also be a good idea to write about that directly in the API docs :)

**Comment by tikkat** [comment]
Maybe the global error could be a separate page looking something like this? 
![error message](https://cloud.githubusercontent.com/assets/3510315/23103393/2674ffc0-f6bb-11e6-93f5-2c7d74734522.png)

(this being the error for missing info in profile)

Don't know if it's to messy with different labels on the buttons depending on the error aso, but it might work? One primary and one secondary action per error, then a title text and text body. What you think @buren @bex1 @bellevik ?

**Comment by buren** [comment]
My vote is on trying to keep the user on the page where the error occurred as much as possible one very common thing that users (and I think we all do) is to refresh the page if an error occurs. So we need to make sure that they hit the same page if they do that :)
