### ISSUE TITLE
Add gender to edit profile page

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#305]
Currently we don't have the gender field displayed on the user profile page, so now its only possible to add that info when registering 😜 

Thanks @bex1 for pointing it out 👍 https://github.com/justarrived/just-match-web/issues/292#issuecomment-279989603 (next time convert it to an issue directly) :)

**Comment by bellevik** [comment]
Nice! I asked about this but didn't get a response, I agree that it should be in the profile page as well. I'm on it!

**Comment by buren** [comment]
@bellevik sorry about not giving you an response before, must have missed it 😳
