### ISSUE TITLE
Imported users are being displayed  :) 

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#313]
**Comment:**
Users that are imported from Wintrgarden can't update their profiles (Anna had this problem with the user `Fayez *******`, we have an OK to log in to his profile). When trying to add new info to the profile nothing is displayed, which should be the case. Sometimes it works, sometimes it doesn't, be aware :)

I assume this has to do with the API in some way? How things are exported? 

_Update:_
Talk to Anna, but it seems like this user wasn't completely imported but only parts of the data.. might affect the bug.

**Screenshots:**
(More screenshots can be found pinned in the dev channel on slack for privacy reasons)
![pasted image at 2017_02_17 09_41 am 1](https://cloud.githubusercontent.com/assets/3510315/23058561/d49e0e92-f4f5-11e6-8e3f-aed8ccfa9abe.png)

![pasted image at 2017_02_17 09_42 am](https://cloud.githubusercontent.com/assets/3510315/23058562/d49eb860-f4f5-11e6-8a86-263fc1fd2ad9.png)

Dev console:
![image](https://cloud.githubusercontent.com/assets/3510315/23058771/ced92298-f4f6-11e6-8600-aa19d1fd760a.png)

**Comment by buren** [comment]
@tikkat when this happens always check the Chrome dev tools and see what the API returns, makes it _a lot_ easier to debug. (Don't forget to remove any personal info.)

**Comment by tikkat** [comment]
great feedback, thanks @buren! See the description, I added the error message from the dev console

**Comment by buren** [comment]
Fixed it :) 🔪 🐛

**Comment by tikkat** [comment]
👑  @buren
