### ISSUE TITLE
Design touchup of chat in job details view (in connection to #298)

### ISSUE THREAD

**Issue by tikkat** [justarrived/just-match-web#322]
**Comment:**
The current design looks like following:
![image](https://cloud.githubusercontent.com/assets/3510315/23135266/307d42a6-f798-11e6-842c-d4e88bbb19e4.png)

We would like to change it a little:
![job chat](https://cloud.githubusercontent.com/assets/3510315/23135278/3b6b70ca-f798-11e6-8e87-e568bb8c483f.png)

This task can (or maybe should) be done by the same person that implemented #298 since they are building on the same design :)

**Comment by buren** [comment]
Awesome 😻
