### ISSUE TITLE
Expose Users' documents attribute to frontend

### ISSUE THREAD

**Issue by bellevik** [justarrived/just-match-web#359]
### Expose Users' documents attribute to frontend

**Description:**
Exposing the documents attribute means the frontend has access to the Users' Documents. The User can see if he/she has uploaded a document before, which might save them some confusion.
**Definition of done:**
When the User can see that a document (resume) has previously been uploaded

**Comment by buren** [comment]
Implemented in the API `GET /api/v1/users/:id/documents`, also supports including `Document` with `?include=document` param.

---

See https://sandbox-api.justarrived.xyz/api_docs/1.0/user_documents/index.html

**Comment by buren** [comment]
## Screenshot

<img width="524" alt="screen shot 2017-03-03 at 15 30 28" src="https://cloud.githubusercontent.com/assets/922411/23554666/57b274a4-0026-11e7-991b-fdc81d615cb1.png">
