### ISSUE TITLE
Production env

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#36]
__Client__

- [x] Properly minify & "treeshake" `bundle.js`

__Server__

- [ ] Deploy to server

See example: https://github.com/vladotesanovic/angular2-express-slim

**Comment by belev** [comment]
I started looking at solutions for AoT and tree shaking. It reduce the size of the bundle more than twice. However there are some problems for now to integrate in the project because of some of the third party libraries.

I can tell you when I make it work.

**Comment by belev** [comment]
@buren the build is ready although it is not only a production build. You can have a look in the pull request I made.

**Comment by buren** [comment]
Fixed in https://github.com/justarrived/just-match-web/pull/77

**Comment by belev** [comment]
[Good article](https://medium.com/@ryanchenkie_40935/angular-cli-deployment-host-your-angular-2-app-on-heroku-3f266f13f352#.w6iryv8b2) for deploying Angular 2 app using Angular CLI. Maybe before deploying you can have a look.

**Comment by buren** [comment]
@belev thanks 👍

**Comment by buren** [comment]
@bvangelov see the comment by @belev if you pick up the deploy task.

**Comment by bvangelov** [comment]
@buren Should I deploy through my account on heroku or will you give me credentials for it? Do you have an account setup for the project or something?

**Comment by buren** [comment]
@bvangelov I created a new Heroku app named `just-match-web-sandbox` and I've invited you as a collaborator (your Gmail address) @bex1 and @tikkat I've invited you too 😉 (justarrived.se addresses).

https://dashboard.heroku.com/apps/just-match-web-sandbox

**Comment by bvangelov** [comment]
@buren in the heroku dashboard, under the deploy tab, could you connect the just-match-web GitHub repo with heroku (it requires admin access). There is no point in initializing heroku repo in the project and pushing to two repos. From there I'll commit and tune the config files for the deploy.

**Comment by buren** [comment]
@bvangelov I've connected the Heroku app with the GitHub repo.

**Comment by buren** [comment]
Done & :shipit:
