### ISSUE TITLE
Unify date format

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#361]
This screenshot really says it all: 

![screen shot 2017-02-27 at 12 45 59](https://cloud.githubusercontent.com/assets/922411/23360257/ab466f2e-fcea-11e6-8fe8-9771c0ee1fc4.png)

**Comment by bex1** [comment]
hehe 🙄

**Comment by buren** [comment]
Those date formats are also dependent on locale so we should make those formatting decisions in a util that is passed the current locale.
