### ISSUE TITLE
Arabic Faq Page (Q & A) incomplete and need aligning 

### ISSUE THREAD

**Issue by xEPIx** [justarrived/just-match-web#371]
Just noticed this:
![just arrived 3-3-2017 3-39-36 pm](https://cloud.githubusercontent.com/assets/16858071/23555074/cd202e56-0027-11e7-877c-f5610a9e731b.png)

1. The Faq is only showing 2 items out of many, incomplete.
2. should be aligned to right as Arabic.

**Comment by buren** [comment]
@bex1 any idea how we best expose what the current locale/direction of the locale is to each of our components? Seems a bit annoying to have to pass the current locale to each and every component.

**Comment by bex1** [comment]
@buren Please provide the rest of the FAQ items on arabic when possible.
We can discuss the alignment of arabic text on wednesday.

**Comment by bex1** [comment]
Closed in favor of #453
