### ISSUE TITLE
When selecting a skill/language the proficiency should default to "blank" not "beginner"

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#383]
Currently when you chose a language or a skill the proficiency is automatically filled in as `Beginner`, many users miss that and just move on and save the form (with the wrong proficiency!).

It is quite urgent that we fix this, since we're currently getting "bad" data..

---

![pasted image 0 1](https://cloud.githubusercontent.com/assets/922411/23745049/176fa228-04b7-11e7-962a-52f87a64eb57.png)

---

❤️  to @annahornmark for reporting this

**Comment by bex1** [comment]
To not set any default value would cause errors on save which would point to a proficiency. But not which specific proficiency. Maybe its more obvious now with the new design based on rating. Also its bad UX to force people to perform additonal steps before saving. One should be able to save and then continue setting proficiencies later.

@buren 

Alternative 1: Remove the requirement for a set proficiency in the api.
Alternative 2: Provide error pointer to proficiency_languageID or something similar so one can show an error at an unfilled proficiency.
Alternative 3: Default to proficiency 3.

**Comment by buren** [comment]
Go for _alternative 1_
