### ISSUE TITLE
Arabic Aligning - homepage_top_banner

### ISSUE THREAD

**Issue by xEPIx** [justarrived/just-match-web#445]
on https://justarrived.se/ar/ 

`.homepage_top_banner_v2_bottom_container .homepage_top_banner_v2_bottom_container_left {
    text-align: left;
`
Should be right, Also:

`.homepage_top_banner_v2_bottom_container .homepage_top_banner_v2_bottom_container_right .cta-text {
    width: 60%;
    height: auto;
    max-width: 120px;
    display: inline-block;
    text-align: left;
}`

text align should be right here.

This will fix the aligning issue on the top banner.

**Comment by bex1** [comment]
This issue was moved to justarrived/just_match_api#1097
