### ISSUE TITLE
Apply button can be under the fold

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#470]
We recently got a support ticket for a user that didn't realise that he could/should scroll down to find it.

<img width="1436" alt="screen shot 2017-05-12 at 16 04 15" src="https://cloud.githubusercontent.com/assets/922411/26001429/9fcef838-372c-11e7-8f2b-137c87c6d2b8.png">

We should make sure that the button is above the fold on 11" screens.

**Comment by bex1** [comment]
That solution wont work since the forms can be alot longer than that. Register form etc.

I will investigate how visible the scrollbar is however.

**Comment by bex1** [comment]
Closing this. The scrollbar is there 😞
