### ISSUE TITLE
App will brake for browsers without localstorage and Safari Incognito mode

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#48]
For example Safari in incognito mode has a known "bug" with localstorage, see https://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an.

**Comment by buren** [comment]
This has been partially fixed. Our storage module fallbacks to an in memory store, if there is no `localStorage` support. However the in memory store isn't great, since it will be completely reset, and the user will be logged out etc, if the user decides to refresh the page.

**Comment by tikkat** [comment]
@buren I'll set this as a P3 bug, or do you think that this is something that we need to prioritize at this point?

**Comment by buren** [comment]
Fixed in https://github.com/justarrived/just-match-web/pull/79
