### ISSUE TITLE
Job card arabic bug

### ISSUE THREAD

**Issue by buren** [justarrived/just-match-web#498]
<img width="305" alt="screen shot 2017-06-02 at 18 12 17" src="https://cloud.githubusercontent.com/assets/922411/26734641/0f9e6eda-47bf-11e7-954f-c0996fb323db.png">

**Comment by bex1** [comment]
wtf. that looks so strange. only happens at that card but all cards have the same setup.

**Comment by buren** [comment]
@bex1 seems like it could be the truncate function clipping the HTML in the middle?

**Comment by bex1** [comment]
@buren This is something in the backend on machine translated non markdown fields when translating to arabic.

**Comment by bex1** [comment]
Was a bug in the API
